import { BREAKPOINT_QUERIES } from "./constants";
import { googleFontCssUrl } from "../assets/googleFonts";
import type { DesignProject, GoogleFontAsset, StyleRule } from "../types";

const BLOCKED_VALUE_PATTERNS = [
  /<\/?style/i,
  /javascript\s*:/i,
  /expression\s*\(/i,
  /behavior\s*:/i,
  /-moz-binding/i,
  /[{};]/
];

export function sanitizeCssValue(property: string, value: string): string | null {
  const trimmed = value.trim();
  if (!trimmed) return "";
  if (trimmed.length > 1000) return null;
  if (BLOCKED_VALUE_PATTERNS.some((pattern) => pattern.test(trimmed))) return null;

  if (
    typeof CSS !== "undefined" &&
    typeof CSS.supports === "function" &&
    !property.startsWith("--") &&
    !CSS.supports(property, trimmed)
  ) {
    return null;
  }

  return trimmed;
}

export function isSafeSelector(selector: string): boolean {
  const trimmed = selector.trim();
  if (!trimmed || trimmed.length > 500 || /[{}@;]/.test(trimmed)) return false;
  try {
    document.querySelector(trimmed);
    return true;
  } catch {
    return false;
  }
}

export function usedGoogleFontAssets(
  rules: StyleRule[],
  fontAssets: GoogleFontAsset[]
): GoogleFontAsset[] {
  return fontAssets.flatMap((asset) => {
    const selectors = new Set(
      rules
        .filter((rule) =>
          rule.declarations["font-family"]
            ?.toLowerCase()
            .includes(asset.family.toLowerCase())
        )
        .map((rule) => rule.selector)
    );
    if (selectors.size === 0) return [];

    const relatedRules = rules.filter((rule) => selectors.has(rule.selector));
    const weights = Array.from(
      new Set(
        relatedRules
          .map((rule) => Number(rule.declarations["font-weight"]))
          .filter((weight) => Number.isInteger(weight) && weight >= 100 && weight <= 900)
      )
    ).sort((a, b) => a - b);
    const styles = Array.from(
      new Set(
        relatedRules
          .map((rule) => rule.declarations["font-style"])
          .filter((style) => style === "normal" || style === "italic")
      )
    );

    return [
      {
        ...asset,
        weights: weights.length > 0 ? weights : [400],
        styles: styles.length > 0 ? styles : ["normal"]
      }
    ];
  });
}

function formatDeclarations(declarations: Record<string, string>): string[] {
  return Object.entries(declarations)
    .filter(([, value]) => value.trim() !== "")
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([property, value]) => `  ${property}: ${value};`);
}

export function rulesToCss(
  rules: StyleRule[],
  includeComment = true,
  fontAssets: GoogleFontAsset[] = []
): string {
  const grouped = new Map<string, Map<string, string>>();

  for (const rule of rules) {
    if (!isSafeSelector(rule.selector)) continue;
    const media = rule.mediaQuery ?? BREAKPOINT_QUERIES[rule.breakpoint] ?? "base";
    const key = media || "base";
    const selectorRules = grouped.get(key) ?? new Map<string, string>();
    const current = selectorRules.get(rule.selector) ?? "";
    const next = new Map<string, string>();

    for (const line of current.split("\n")) {
      const match = line.trim().match(/^([\w-]+):\s*(.+);$/);
      if (match) next.set(match[1], match[2]);
    }
    for (const [property, value] of Object.entries(rule.declarations)) {
      const cleanValue = sanitizeCssValue(property, value);
      if (cleanValue) next.set(property, cleanValue);
    }

    selectorRules.set(
      rule.selector,
      Array.from(next.entries())
        .map(([property, value]) => `  ${property}: ${value};`)
        .join("\n")
    );
    grouped.set(key, selectorRules);
  }

  const output: string[] = [];
  if (includeComment) output.push("/* Generated by Visual Style Editor */", "");
  const usedAssets = usedGoogleFontAssets(rules, fontAssets);
  for (const asset of usedAssets) {
    output.push(
      `@import url("${googleFontCssUrl(asset.family, asset.weights, asset.styles)}");`
    );
  }
  if (usedAssets.length > 0) output.push("");

  const base = grouped.get("base");
  if (base) {
    for (const [selector, declarations] of base.entries()) {
      if (!declarations) continue;
      output.push(`${selector} {`, declarations, "}", "");
    }
  }

  for (const [media, selectors] of grouped.entries()) {
    if (media === "base") continue;
    const inner: string[] = [];
    for (const [selector, declarations] of selectors.entries()) {
      if (!declarations) continue;
      inner.push(`  ${selector} {`);
      inner.push(...declarations.split("\n").map((line) => `  ${line}`));
      inner.push("  }", "");
    }
    if (inner.length > 0) {
      output.push(`@media ${media} {`, ...inner.slice(0, -1), "}", "");
    }
  }

  return output.join("\n").trimEnd() + (output.length > 0 ? "\n" : "");
}

export function ruleDeclarationsToInlineCss(rule: StyleRule): string {
  return formatDeclarations(rule.declarations).join("\n");
}

export function serializeDesignBackup(designs: DesignProject[]): string {
  return JSON.stringify(
    {
      schemaVersion: 1,
      exportedAt: new Date().toISOString(),
      designs
    },
    null,
    2
  );
}

export function downloadTextFile(filename: string, content: string, type: string): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.setAttribute("data-vse-download", "true");
  anchor.href = url;
  anchor.download = filename;
  anchor.style.display = "none";
  document.documentElement.append(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function copyText(value: string): Promise<void> {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(value);
    return;
  }
  const textarea = document.createElement("textarea");
  textarea.value = value;
  textarea.style.position = "fixed";
  textarea.style.opacity = "0";
  document.documentElement.append(textarea);
  textarea.select();
  document.execCommand("copy");
  textarea.remove();
}

export function validateImportedProject(input: unknown, hostname: string): DesignProject {
  if (!input || typeof input !== "object") throw new Error("Project must be an object.");
  const candidate = input as Partial<DesignProject>;
  if (candidate.schemaVersion !== 1) throw new Error("Unsupported project version.");
  if (candidate.hostname !== hostname) {
    throw new Error(`This project belongs to ${candidate.hostname || "another domain"}.`);
  }
  if (!Array.isArray(candidate.rules) || candidate.rules.length > 1000) {
    throw new Error("Project rules are missing or exceed the safe limit.");
  }

  const rules: StyleRule[] = candidate.rules.map((rule) => {
    if (!rule || typeof rule !== "object" || !isSafeSelector(rule.selector)) {
      throw new Error("Project contains an unsafe selector.");
    }
    const declarations: Record<string, string> = {};
    for (const [property, value] of Object.entries(rule.declarations ?? {})) {
      if (!/^--?[\w-]+$|^[a-z][\w-]*$/.test(property) || typeof value !== "string") {
        throw new Error("Project contains an invalid CSS declaration.");
      }
      const clean = sanitizeCssValue(property, value);
      if (clean === null) throw new Error("Project contains an unsafe CSS value.");
      if (clean) declarations[property] = clean;
    }
    return {
      id: String(rule.id || `${rule.selector}-${rule.breakpoint}`),
      selector: rule.selector,
      declarations,
      breakpoint: ["base", "desktop", "tablet", "mobile"].includes(rule.breakpoint)
        ? rule.breakpoint
        : "base",
      mediaQuery:
        typeof rule.mediaQuery === "string" && /^\([^)]+\)$/.test(rule.mediaQuery)
          ? rule.mediaQuery
          : undefined,
      updatedAt: Number(rule.updatedAt) || Date.now()
    } as StyleRule;
  });

  const fontAssets: GoogleFontAsset[] = Array.isArray(candidate.fontAssets)
    ? candidate.fontAssets.slice(0, 100).map((asset) => {
        if (
          !asset ||
          typeof asset.family !== "string" ||
          !/^[\p{L}\p{N}\s-]{1,100}$/u.test(asset.family) ||
          typeof asset.category !== "string"
        ) {
          throw new Error("Project contains invalid Google Fonts metadata.");
        }
        return {
          family: asset.family,
          category: asset.category,
          weights: Array.isArray(asset.weights)
            ? asset.weights
                .map(Number)
                .filter((weight) => weight >= 100 && weight <= 900)
                .slice(0, 9)
            : [400],
          styles: Array.isArray(asset.styles)
            ? asset.styles.filter((style) => style === "normal" || style === "italic")
            : ["normal"],
          subsets: Array.isArray(asset.subsets)
            ? asset.subsets.filter((subset) => typeof subset === "string").slice(0, 30)
            : []
        };
      })
    : [];

  const now = Date.now();
  return {
    schemaVersion: 1,
    id: String(candidate.id || `imported-${now}`),
    name: String(
      candidate.name || `Imported design ${new Date(now).toLocaleDateString()}`
    ),
    hostname,
    sourceUrl: String(candidate.sourceUrl || location.href),
    scope: candidate.scope === "page" ? "page" : "domain",
    enabled: candidate.enabled !== false,
    rules,
    fontAssets,
    textOverrides: [],
    createdAt: Number(candidate.createdAt) || now,
    updatedAt: now
  };
}
