import { describe, expect, it } from "vitest";
import { rulesToCss, sanitizeCssValue } from "../../src/utils/css";
import type { StyleRule } from "../../src/types";

function rule(partial: Partial<StyleRule>): StyleRule {
  return {
    id: partial.id ?? "rule-1",
    selector: partial.selector ?? ".hero",
    declarations: partial.declarations ?? {},
    breakpoint: partial.breakpoint ?? "base",
    updatedAt: 1,
    mediaQuery: partial.mediaQuery
  };
}

describe("CSS generation", () => {
  it("groups base and responsive declarations", () => {
    const css = rulesToCss([
      rule({
        declarations: { color: "#ffffff", "font-size": "40px" }
      }),
      rule({
        id: "rule-2",
        breakpoint: "mobile",
        declarations: { "font-size": "24px" }
      })
    ]);

    expect(css).toContain("/* Generated by Visual Style Editor */");
    expect(css).toContain(".hero {");
    expect(css).toContain("color: #ffffff;");
    expect(css).toContain("@media (max-width: 768px)");
    expect(css).toContain("font-size: 24px;");
  });

  it("merges duplicate selector rules at the same breakpoint", () => {
    const css = rulesToCss([
      rule({ declarations: { color: "red" } }),
      rule({ id: "rule-2", declarations: { color: "blue", display: "flex" } })
    ]);
    expect(css.match(/\.hero \{/g)).toHaveLength(1);
    expect(css).toContain("color: blue;");
    expect(css).toContain("display: flex;");
  });

  it("blocks style and JavaScript injection tokens", () => {
    expect(sanitizeCssValue("color", "red; } body { display:none")).toBeNull();
    expect(sanitizeCssValue("background-image", "url(javascript:alert(1))")).toBeNull();
    expect(sanitizeCssValue("color", "#6d5dfc")).toBe("#6d5dfc");
  });

  it("exports only used Google Font imports", () => {
    const css = rulesToCss(
      [
        rule({
          declarations: {
            "font-family": '"Noto Kufi Arabic", sans-serif',
            "font-weight": "700"
          }
        })
      ],
      true,
      [
        {
          family: "Noto Kufi Arabic",
          category: "sans-serif",
          weights: [400, 700],
          styles: ["normal", "italic"],
          subsets: ["arabic", "latin"]
        },
        {
          family: "Roboto",
          category: "sans-serif",
          weights: [400],
          styles: ["normal"],
          subsets: ["latin"]
        }
      ]
    );
    expect(css).toContain("family=Noto+Kufi+Arabic:wght@700");
    expect(css).not.toContain("Noto+Kufi+Arabic:ital");
    expect(css).not.toContain("Noto+Kufi+Arabic:wght@400");
    expect(css).not.toContain("family=Roboto");
  });
});
